### ISSUE TITLE
[BUG] `AttributeError` inside `Case.call` when `httpx.AsyncClient` is used as `session`

### ISSUE THREAD

**Issue by kimvais** [schemathesis/schemathesis#1873]
### Checklist

- [X] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [X] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [X] I am using the latest version of Schemathesis

### Describe the bug
The change introduced in https://github.com/schemathesis/schemathesis/pull/1828/
causes all of our tests to fail with
```
>       response.verify = verify  # type: ignore[attr-defined]
E       AttributeError: 'coroutine' object has no attribute 'verify'
```

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. generate pytest fixture with `schemathesis.from_asgi(...)`
2. generate test schema from the fixture with `schemathesis.from_pytest_fixture()` using the fixture you just defined
3. parameterize a test case with above schema's `.parametrize()`
5. `with httpx.AsyncClient(...) as client:` do
6. `await case.call(session=client)`

### Expected behavior

The test to run instead of throwing an exception

### Environment

```
- OS: Linux (although probably irrelevant)
- Python version: 3.11
- Schemathesis version: 3.20.2
- Spec version: OpenAPI 3.x (although probably irrelevant)
```

**Comment by Stranger6667** [comment]
Hi @kimvais 

Thank you for reporting! 

First, I need to note that I want to support such a use case!

However `httpx.AsyncClient` has never meant to be supported as a `session` for `Case.call`, and it used to work by accident and the `Case.call` signature [declares](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/models.py#L330) `session` to be `Optional[requests.Session]`.

I planned to work on the transport layer in the next minor release, therefore I think that I'll include supporting `httpx` including `AsyncClient`. It also happened that @svtkachenko submitted a [PR](https://github.com/schemathesis/schemathesis/pull/1871) that adds partial support for validating `httpx` responses, so I think including more `httpx` related stuff in the next release makes sense.

If you have any other areas that would benefit from better `httpx` support (checks, custom hooks), please let me know.

**Comment by kimvais** [comment]
Hey!

NP!

Unfortunately Don't really know the code that demonstrated this very intimately, it was written by someone else and is currently in maintenance mode so I can't really tell why they chose to use `httpx.AsyncClient` in the first place.

I just made some other fixes and the tests started failing in all pipelines and found this to be the root cause - they hadn't been run since the change was introduced.... 🤦 

As a temporary workaround I've locked the `schematesis` version to an earlier version in our package requirements, but great to hear that this is on your radar so I can remove the version locking for our package once this gets closed!

**Comment by Stranger6667** [comment]
> Unfortunately I don't really know the code that demonstrated this very intimately, it was written by someone else and is currently in maintenance mode so I can't really tell why they chose to use httpx.AsyncClient in the first place.
> I just made some other fixes and the tests started failing in all pipelines and found this to be the root cause - they hadn't been run since the change was introduced.... 🤦

Understood! :)

> As a temporary workaround I've locked the schematesis version to an earlier version in our package requirements, but great to hear that this is on your radar so I can remove the version locking for our package once this gets closed!

Cool! I may issue some patch releases before jumping into the `httpx` issue, but I'll keep you updated :)

**Comment by Stranger6667** [comment]
Closing this, as we have #1718 and this issue is more or less about the same thing - will work on proper support there.
