### ISSUE TITLE
[BUG]Parsing security

### ISSUE THREAD

**Issue by ludeknovy** [schemathesis/schemathesis#2472]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

When running schemathesis from pytest, I have a custom Auth class, which sets the token based on the swagger security schema. To get the auth mechanism I was doing it like this: `security: list = context.operation.definition.get("security")`.
It has been working fine until v 3.29.0. It seems to be connected to the change of the parsing library?

```
/site-packages/schemathesis/specs/openapi/security.py:8: DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
    from jsonschema import RefResolver
```

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

test.py
```
@schemathesis.auth()
class CustomAuth:

    def get(self, case, context):
        print(context.operation)
        security: list = context.operation.definition.get("security")
        if any("UserBearerAuth" in dic for dic in security):
            return "token"


    def set(self, case, data, context):
        case.headers = case.headers or {}
        case.headers["Authorization"] = f"Bearer {data}"
        
        
@schema.auth(CustomAuth)
@schema.parametrize()
def test_api(case):
    case.call_and_validate()
```

pytest test.py

2. See error:

```
   security: list = context.operation.definition.get("security")
E   AttributeError: 'OperationDefinition' object has no attribute 'get'
```

Please include a minimal API schema causing this issue:

```yaml
securitySchemes:
    UserBearerAuth:
      bearerFormat: JWT
      description: "JWT token"
      scheme: bearer
      type: http
```

### Expected behavior

The `security` schema name is available again

### Environment

```
- OS: [MacOS]
- Python version: [3.10]
- Schemathesis version: [3.36.1]
- Spec version: [ Open API 3.0.1]
```

### Additional context

Include any other relevant details, like logs or screenshots.

**Comment by Stranger6667** [comment]
Btw, the underlying parsing library is the same, but `jsonschema` deprecated that way of reference resolution in favor of `referencing` (which is fantastic in my opinion). I want to migrate to it, and there is even an open PR for that, but it is not ready yet.

**Comment by ludeknovy** [comment]
Thanks a lot. I can confirm the `definition.resolved.get("security")` works fine with 3.36.1
