### ISSUE TITLE
[BUG] TypeError: settings.__init__() got an unexpected keyword argument '_fallback' with hypothesis >= 6.131.4

### ISSUE THREAD

**Issue by flashcode** [schemathesis/schemathesis#2797]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

Error when running WeeChat API tests with hypothesis >= 6.131.4 (work fine with hypothesis 6.131.3).

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. Run the WeeChat CI (Actions) of branch "main".
2. The API tests fail with the following error:

```
An internal error occurred during the test run

    Traceback (most recent call last):
      File "/opt/pipx/venvs/schemathesis/lib/python3.12/site-packages/schemathesis/cli/__init__.py", line 1422, in into_event_stream
        yield from runner.from_schema(
      File "/opt/pipx/venvs/schemathesis/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 258, in _generate_events
        yield from self._execute(ctx)
      File "/opt/pipx/venvs/schemathesis/lib/python3.12/site-packages/schemathesis/runner/impl/solo.py", line 20, in _execute
        for event in self._execute_impl(ctx):
      File "/opt/pipx/venvs/schemathesis/lib/python3.12/site-packages/schemathesis/runner/impl/solo.py", line 28, in _execute_impl
        yield from self._run_tests(
      File "/opt/pipx/venvs/schemathesis/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 409, in _run_tests
        for result in maker(
      File "/opt/pipx/venvs/schemathesis/lib/python3.12/site-packages/schemathesis/schemas.py", line 289, in get_all_tests
        test = create_test(
               ^^^^^^^^^^^^
      File "/opt/pipx/venvs/schemathesis/lib/python3.12/site-packages/schemathesis/_hypothesis.py", line 102, in create_test
        wrapped_test._hypothesis_internal_use_settings = hypothesis.settings(
                                                         ^^^^^^^^^^^^^^^^^^^^
    TypeError: settings.__init__() got an unexpected keyword argument '_fallback'

Tip: Please consider reporting the traceback above to our issue tracker:

  https://github.com/schemathesis/schemathesis/issues/new?labels=Status%3A%20Needs%20Triage%2C+Type%3A+Bug&template=bug_report.md&title=%5BBUG%5D.
```

CI example: https://github.com/weechat/weechat/actions/runs/14557119156/job/40835506022 (see Test Relay OpenAPI).

### Expected behavior

Tests are OK with no such internal error.

### Environment

```
- OS: Linux
- Python version: 3.12 or 3.13
- Schemathesis version: 3.39.15
- Hypothesis version: 6.131.6
- Spec version: Open API 3.1.0
```

### Additional context

The bug seems related to internal refactoring in hypothesis settings done in version 6.131.4, which are supposed to have no user impact.

So I'm not sure if the bug is in schemathesis or hypothesis (I did not dig enough).

**Comment by Stranger6667** [comment]
Hi! Thanks for reporting! I am going to fix it soon.

Schemathesis relies on some internals of Hypothesis (in some cases there is no other way), and in this case the Schemathesis side wasn't robust enough to be forward compatible with that refactoring.

**Comment by Stranger6667** [comment]
The fix is released in 3.39.16

**Comment by flashcode** [comment]
Thanks for the quick fix, it works fine! 👍🏻
